### ISSUE TITLE
Trying to get it to AfM working with Appium Desktop Inspector

### ISSUE THREAD

**Issue by dietertong** [appium/appium-for-mac#111] opened 2020-11-23 21:26 UTC
Hi all,

Trying to get some familiarity with Appium For Mac and running into an issue where I cannot for the life of me figure out how to get the app to appear in the inspector from Appium Desktop.

I compiled and installed Appium For Mac to /Applications
Appium Desktop is installed.
I start the server on Appium Desktop, open up the Inspector Custom Session
Remote Host and Remote port are default (0.0.0.0 and 4723 respectively)
Have platformName set to 'mac'
Have deviceName set to 'mac'
Have app set to 'calculator'
Click Start session

I see Appium For Mac starting in the server logs, I see the Calculator app appear, but in the Inspector it just shows my desktop still instead of just the calculator app.
Both Appium For Mac and Appium Desktop have Accessibility and Screen Recording enabled under Security & Privacy
Running macOS 10.15.7.

Any idea what I am missing? Any help is appreciated. Thanks!

**Comment by yeucodonvn** [comment] 2020-12-31 15:34
same too. i cannot find a tutorial or video on it

**Comment by KazuCocoa** [comment] 2020-12-31 23:15
> it just shows my desktop still instead of just the calculator app.

It seems it was by design in Mac driver. Mac driver calls screenshot command to take a screenshot.

https://github.com/appium/appium-mac2-driver/pull/40 can take a screenshot only the AUT (It hasn't merged yet though.)

**Comment by KazuCocoa** [comment] 2021-01-01 19:51
Currently, AD does not design to work with non Android/iOS drivers fully.
I've created an issue https://github.com/appium/appium-desktop/issues/1659 to for mac2 driver for now.

**Comment by KazuCocoa** [comment] 2021-01-01 19:51
> AD does not design to work with non Android/iOS drivers fully.

**Closed by KazuCocoa** 2021-01-01 19:51 UTC
